In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, count, when, isnan, lit, desc, hour, dayofmonth, dayofweek
from pyspark.sql.functions import split, regexp_extract
from pyspark.sql.types import DoubleType, FloatType

spark = SparkSession.builder \
    .appName("Analisis Ecommerce Octubre") \
    .config("spark.driver.memory", "6g") \
    .getOrCreate()

spark

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
file_path = "/content/drive/MyDrive/Big Data/2019-Oct.csv"

df = (spark.read.option("header", True)
          .option("inferSchema", True)
          .csv(file_path))
df.show(5, truncate=False)

+-------------------+----------+----------+-------------------+-----------------------------------+--------+-------+---------+------------------------------------+
|event_time         |event_type|product_id|category_id        |category_code                      |brand   |price  |user_id  |user_session                        |
+-------------------+----------+----------+-------------------+-----------------------------------+--------+-------+---------+------------------------------------+
|2019-10-01 00:00:00|view      |44600062  |2103807459595387724|NULL                               |shiseido|35.79  |541312140|72d76fde-8bb3-4e00-8c23-a032dfed738c|
|2019-10-01 00:00:00|view      |3900821   |2053013552326770905|appliances.environment.water_heater|aqua    |33.2   |554748717|9333dfbd-b87a-4708-9857-6336556b0fcc|
|2019-10-01 00:00:01|view      |17200506  |2053013559792632471|furniture.living_room.sofa         |NULL    |543.1  |519107250|566511c2-e2e3-422b-b695-cf8e6e792ca8|
|2019-10-01 00:00:01|view      |1307067   |2053013558920217191|computers.notebook                 |lenovo  |251.74 |550050854|7c90fc70-0e80-4590-96f3-13c02c18c713|
|2019-10-01 00:00:04|view      |1004237   |2053013555631882655|electronics.smartphone             |apple   |1081.98|535871217|c6bd7419-2748-4c56-95b4-8cec9ff8b80d|
+-------------------+----------+----------+-------------------+-----------------------------------+--------+-------+---------+------------------------------------+
only showing top 5 rows

In [11]:
df.printSchema()

root
 |-- event_time: timestamp (nullable = true)
 |-- event_type: string (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- category_id: long (nullable = true)
 |-- category_code: string (nullable = true)
 |-- brand: string (nullable = true)
 |-- price: double (nullable = true)
 |-- user_id: integer (nullable = true)
 |-- user_session: string (nullable = true)

## Estadísticas

In [12]:
#Numero de registros y columnas
num_rows = df.count()
num_cols = len(df.columns)

print(f"Número de registros: {num_rows:,}")
print(f"Número de columnas: {num_cols}")

Número de registros: 42,448,764
Número de columnas: 9

In [ ]:
#Estadísticas de variable precio
df.select("price").describe().show()
price_percentiles = df.approxQuantile("price", [0.25, 0.5, 0.75], 0.01)

print("Percentil 25:", price_percentiles[0])
print("Mediana:", price_percentiles[1])
print("Percentil 75:", price_percentiles[2])

+-------+-----------------+
|summary|            price|
+-------+-----------------+
|  count|         42448764|
|   mean|290.3236606848809|
| stddev|358.2691553394021|
|    min|              0.0|
|    max|          2574.07|
+-------+-----------------+

Percentil 25: 64.78
Mediana: 161.83
Percentil 75: 357.8

In [ ]:
#Frecuencia de event_type
event_type_counts = df.groupBy("event_type") \
                      .count() \
                      .withColumn("percentage", (col("count") / lit(num_rows)) * 100) \
                      .orderBy(desc("count"))

event_type_counts.show(truncate=False)

+----------+--------+------------------+
|event_type|count   |percentage        |
+----------+--------+------------------+
|view      |40779399|96.06734132470854 |
|cart      |926516  |2.182668970055288 |
|purchase  |742849  |1.7499897052361761|
+----------+--------+------------------+

In [ ]:
#Valores faltantes por columna
from pyspark.sql.functions import col, count, when, isnan
import pandas as pd

# Número total de registros
num_rows = df.count()

# Crear expresiones para contar valores faltantes
missing_exprs = []

for c, dtype in df.dtypes:
    if dtype in ["double", "float"]:
        missing_exprs.append(
            count(when(col(c).isNull() | isnan(col(c)), c)).alias(c)
        )
    else:
        missing_exprs.append(
            count(when(col(c).isNull(), c)).alias(c)
        )

# Ejecutar conteo de nulos
missing_result = df.select(missing_exprs).collect()[0].asDict()

# Convertir a Pandas para evitar error de Python worker en Spark
missing_summary_pd = pd.DataFrame(
    list(missing_result.items()),
    columns=["variable", "missing_values"]
)

missing_summary_pd["missing_percentage"] = (
    missing_summary_pd["missing_values"] / num_rows
) * 100

missing_summary_pd = missing_summary_pd.sort_values(
    by="missing_percentage",
    ascending=False
)

missing_summary_pd

        variable  missing_values  missing_percentage
4  category_code        13515609           31.839818
5          brand         6113008           14.400909
8   user_session               2            0.000005
0     event_time               0            0.000000
1     event_type               0            0.000000
3    category_id               0            0.000000
2     product_id               0            0.000000
6          price               0            0.000000
7        user_id               0            0.000000

In [ ]:
#Valores únicos por variable
columns_to_check = ["product_id", "category_id", "category_code", "brand", "user_id", "user_session"]

for c in columns_to_check:
    print(f"{c}: {df.select(c).distinct().count():,} valores únicos")

product_id: 166,794 valores únicos
category_id: 624 valores únicos
category_code: 127 valores únicos
brand: 3,446 valores únicos
user_id: 3,022,290 valores únicos
user_session: 9,244,422 valores únicos

In [ ]:
#Categorías más frecuentes
df.groupBy("category_code") \
  .count() \
  .withColumn("percentage", (col("count") / lit(num_rows)) * 100) \
  .orderBy(desc("count")) \
  .show(20, truncate=False)

+--------------------------------+--------+------------------+
|category_code                   |count   |percentage        |
+--------------------------------+--------+------------------+
|NULL                            |13515609|31.839817526842477|
|electronics.smartphone          |11507231|27.108518401148263|
|electronics.clocks              |1311033 |3.088506887974406 |
|computers.notebook              |1137623 |2.6799908708767117|
|electronics.video.tv            |1113750 |2.623751306398462 |
|electronics.audio.headphone     |1100188 |2.591802201826183 |
|appliances.kitchen.refrigerators|887755  |2.0913565351396333|
|appliances.kitchen.washer       |869404  |2.04812559442249  |
|appliances.environment.vacuum   |801670  |1.888559110931946 |
|apparel.shoes                   |763901  |1.7995836109621473|
|auto.accessories.player         |470208  |1.1077071643358096|
|computers.desktop               |424242  |0.9994213259071572|
|apparel.shoes.keds              |410304  |0.9665864476054004|
|furniture.bedroom.bed           |358453  |0.8444368368417041|
|electronics.tablet              |316735  |0.7461583569311936|
|electronics.audio.subwoofer     |313664  |0.7389237528800603|
|furniture.living_room.cabinet   |301410  |0.7100560101113899|
|construction.tools.drill        |279948  |0.6594962340952967|
|electronics.telephone           |247628  |0.5833573858593386|
|auto.accessories.videoregister  |224076  |0.5278740271448187|
+--------------------------------+--------+------------------+
only showing top 20 rows

In [ ]:
#Marcas más frecuentes
df.groupBy("brand") \
  .count() \
  .withColumn("percentage", (col("count") / lit(num_rows)) * 100) \
  .orderBy(desc("count")) \
  .show(20, truncate=False)

+--------+-------+------------------+
|brand   |count  |percentage        |
+--------+-------+------------------+
|NULL    |6113008|14.400909293848931|
|samsung |5282775|12.44506200463222 |
|apple   |4122554|9.711835190301418 |
|xiaomi  |3083763|7.264670886530407 |
|huawei  |1111205|2.617755843256119 |
|lucente |655861 |1.5450650106090251|
|lg      |562404 |1.3249007674287054|
|bosch   |557090 |1.3123821461562462|
|oppo    |482887 |1.1375761141125333|
|sony    |456644 |1.0757533482011397|
|acer    |428153 |1.008634786162443 |
|cordiant|368277 |0.8675800313055051|
|artel   |338203 |0.7967322676344593|
|lenovo  |338103 |0.7964966895149174|
|hp      |305242 |0.7190833636522372|
|indesit |290101 |0.6834144805723907|
|dauscher|289853 |0.6828302468359266|
|philips |282699 |0.6659769881638956|
|redmond |279734 |0.6589920969194769|
|respect |271167 |0.638810119418318 |
+--------+-------+------------------+
only showing top 20 rows

## Particionamiento

In [ ]:
from pyspark.sql.functions import (
    col, when, hour, split, lit, desc, count, coalesce
)

In [ ]:
df_part = df

In [ ]:
df_part = df_part.withColumn(
    "category_group",
    when(
        col("category_code").isNull(),
        "unknown"
    ).otherwise(
        split(col("category_code"), "\\.").getItem(0)
    )
)

df_part.select("category_code", "category_group").show(10, truncate=False)

+-----------------------------------+--------------+
|category_code                      |category_group|
+-----------------------------------+--------------+
|NULL                               |unknown       |
|appliances.environment.water_heater|appliances    |
|furniture.living_room.sofa         |furniture     |
|computers.notebook                 |computers     |
|electronics.smartphone             |electronics   |
|computers.desktop                  |computers     |
|NULL                               |unknown       |
|NULL                               |unknown       |
|apparel.shoes.keds                 |apparel       |
|electronics.smartphone             |electronics   |
+-----------------------------------+--------------+
only showing top 10 rows

In [ ]:
df_part = df_part.withColumn(
    "event_hour",
    hour(col("event_time"))
)

df_part = df_part.withColumn(
    "time_period",
    when((col("event_hour") >= 0) & (col("event_hour") <= 5), "night")
    .when((col("event_hour") >= 6) & (col("event_hour") <= 11), "morning")
    .when((col("event_hour") >= 12) & (col("event_hour") <= 17), "afternoon")
    .when((col("event_hour") >= 18) & (col("event_hour") <= 23), "evening")
    .otherwise("unknown")
)

df_part.select("event_time", "event_hour", "time_period").show(10, truncate=False)

+-------------------+----------+-----------+
|event_time         |event_hour|time_period|
+-------------------+----------+-----------+
|2019-10-01 00:00:00|0         |night      |
|2019-10-01 00:00:00|0         |night      |
|2019-10-01 00:00:01|0         |night      |
|2019-10-01 00:00:01|0         |night      |
|2019-10-01 00:00:04|0         |night      |
|2019-10-01 00:00:05|0         |night      |
|2019-10-01 00:00:08|0         |night      |
|2019-10-01 00:00:08|0         |night      |
|2019-10-01 00:00:10|0         |night      |
|2019-10-01 00:00:11|0         |night      |
+-------------------+----------+-----------+
only showing top 10 rows

In [ ]:
p25 = 64.78
p75 = 357.77

df_part = df_part.withColumn(
    "price_range",
    when(col("price") <= p25, "low")
    .when((col("price") > p25) & (col("price") <= p75), "medium")
    .when(col("price") > p75, "high")
    .otherwise("unknown")
)

df_part.select("price", "price_range").show(10, truncate=False)

+-------+-----------+
|price  |price_range|
+-------+-----------+
|35.79  |low        |
|33.2   |low        |
|543.1  |high       |
|251.74 |medium     |
|1081.98|high       |
|908.62 |high       |
|380.96 |high       |
|41.16  |low        |
|102.71 |medium     |
|566.01 |high       |
+-------+-----------+
only showing top 10 rows

In [ ]:
df_part.select(
    "event_type",
    "category_code",
    "category_group",
    "price",
    "price_range",
    "event_time",
    "event_hour",
    "time_period"
).show(20, truncate=False)

+----------+-----------------------------------+--------------+-------+-----------+-------------------+----------+-----------+
|event_type|category_code                      |category_group|price  |price_range|event_time         |event_hour|time_period|
+----------+-----------------------------------+--------------+-------+-----------+-------------------+----------+-----------+
|view      |NULL                               |unknown       |35.79  |low        |2019-10-01 00:00:00|0         |night      |
|view      |appliances.environment.water_heater|appliances    |33.2   |low        |2019-10-01 00:00:00|0         |night      |
|view      |furniture.living_room.sofa         |furniture     |543.1  |high       |2019-10-01 00:00:01|0         |night      |
|view      |computers.notebook                 |computers     |251.74 |medium     |2019-10-01 00:00:01|0         |night      |
|view      |electronics.smartphone             |electronics   |1081.98|high       |2019-10-01 00:00:04|0         |night      |
|view      |computers.desktop                  |computers     |908.62 |high       |2019-10-01 00:00:05|0         |night      |
|view      |NULL                               |unknown       |380.96 |high       |2019-10-01 00:00:08|0         |night      |
|view      |NULL                               |unknown       |41.16  |low        |2019-10-01 00:00:08|0         |night      |
|view      |apparel.shoes.keds                 |apparel       |102.71 |medium     |2019-10-01 00:00:10|0         |night      |
|view      |electronics.smartphone             |electronics   |566.01 |high       |2019-10-01 00:00:11|0         |night      |
|view      |appliances.kitchen.microwave       |appliances    |51.46  |low        |2019-10-01 00:00:11|0         |night      |
|view      |electronics.smartphone             |electronics   |900.64 |high       |2019-10-01 00:00:11|0         |night      |
|view      |appliances.environment.water_heater|appliances    |102.38 |medium     |2019-10-01 00:00:13|0         |night      |
|view      |NULL                               |unknown       |35.79  |low        |2019-10-01 00:00:15|0         |night      |
|view      |furniture.bedroom.bed              |furniture     |93.18  |medium     |2019-10-01 00:00:16|0         |night      |
|view      |NULL                               |unknown       |357.79 |high       |2019-10-01 00:00:17|0         |night      |
|view      |electronics.video.tv               |electronics   |193.03 |medium     |2019-10-01 00:00:18|0         |night      |
|view      |appliances.kitchen.mixer           |appliances    |58.95  |low        |2019-10-01 00:00:18|0         |night      |
|view      |computers.notebook                 |computers     |580.89 |high       |2019-10-01 00:00:19|0         |night      |
|view      |electronics.smartphone             |electronics   |1747.79|high       |2019-10-01 00:00:19|0         |night      |
+----------+-----------------------------------+--------------+-------+-----------+-------------------+----------+-----------+
only showing top 20 rows

In [ ]:
df_part.groupBy("event_type") \
    .count() \
    .withColumn("probability", col("count") / lit(num_rows)) \
    .withColumn("percentage", col("probability") * 100) \
    .orderBy(desc("count")) \
    .show(truncate=False)

+----------+--------+--------------------+------------------+
|event_type|count   |probability         |percentage        |
+----------+--------+--------------------+------------------+
|view      |40779399|0.9606734132470853  |96.06734132470854 |
|cart      |926516  |0.021826689700552883|2.182668970055288 |
|purchase  |742849  |0.01749989705236176 |1.7499897052361761|
+----------+--------+--------------------+------------------+

In [ ]:
df_part.groupBy("category_group") \
    .count() \
    .withColumn("probability", col("count") / lit(num_rows)) \
    .withColumn("percentage", col("probability") * 100) \
    .orderBy(desc("count")) \
    .show(20, truncate=False)

+--------------+--------+---------------------+--------------------+
|category_group|count   |probability          |percentage          |
+--------------+--------+---------------------+--------------------+
|electronics   |16135623|0.3801199723977829   |38.01199723977829   |
|unknown       |13515609|0.3183981752684248   |31.839817526842477  |
|appliances    |4967294 |0.11701857797320082  |11.701857797320082  |
|computers     |2324217 |0.05475346702674311  |5.475346702674311   |
|apparel       |1542924 |0.03634791345161428  |3.634791345161428   |
|furniture     |1247160 |0.029380360756793768 |2.938036075679377   |
|auto          |1013115 |0.02386677265797421  |2.386677265797421   |
|construction  |730834  |0.01721684994173211  |1.7216849941732109  |
|kids          |520619  |0.012264644501781018 |1.2264644501781017  |
|accessories   |238238  |0.005612366004343495 |0.5612366004343495  |
|sport         |176616  |0.0041606865161020945|0.41606865161020945 |
|medicine      |14806   |3.4879696379381034E-4|0.034879696379381035|
|country_yard  |14089   |3.319060126226526E-4 |0.03319060126226526 |
|stationery    |7620    |1.7951052709096549E-4|0.017951052709096547|
+--------------+--------+---------------------+--------------------+

In [ ]:
df_part.groupBy("price_range") \
    .count() \
    .withColumn("probability", col("count") / lit(num_rows)) \
    .withColumn("percentage", col("probability") * 100) \
    .orderBy(desc("count")) \
    .show(truncate=False)

+-----------+--------+-------------------+------------------+
|price_range|count   |probability        |percentage        |
+-----------+--------+-------------------+------------------+
|medium     |21234978|0.5002496185754667 |50.02496185754667 |
|high       |10700699|0.2520850548204419 |25.208505482044192|
|low        |10513087|0.24766532660409146|24.766532660409148|
+-----------+--------+-------------------+------------------+

In [ ]:
df_part.groupBy("time_period") \
    .count() \
    .withColumn("probability", col("count") / lit(num_rows)) \
    .withColumn("percentage", col("probability") * 100) \
    .orderBy(desc("count")) \
    .show(truncate=False)

+-----------+--------+-------------------+------------------+
|time_period|count   |probability        |percentage        |
+-----------+--------+-------------------+------------------+
|afternoon  |15940761|0.37552945004476457|37.552945004476456|
|morning    |13837692|0.3259857460160677 |32.59857460160677 |
|night      |7526440 |0.177306458204531  |17.730645820453102|
|evening    |5143871 |0.1211783457346367 |12.117834573463671|
+-----------+--------+-------------------+------------------+

In [ ]:
partition_combinations = df_part.groupBy(
    "event_type",
    "category_group",
    "price_range",
    "time_period"
).count()

partition_combinations = partition_combinations.withColumn(
    "probability",
    col("count") / lit(num_rows)
).withColumn(
    "percentage",
    col("probability") * 100
)

partition_combinations.orderBy(desc("count")).show(50, truncate=False)

+----------+--------------+-----------+-----------+-------+---------------------+-------------------+
|event_type|category_group|price_range|time_period|count  |probability          |percentage         |
+----------+--------------+-----------+-----------+-------+---------------------+-------------------+
|view      |electronics   |medium     |afternoon  |3060638|0.0721019344638633   |7.21019344638633   |
|view      |electronics   |medium     |morning    |2595235|0.061138058106945115 |6.113805810694512  |
|view      |electronics   |high       |afternoon  |2207636|0.05200707375131111  |5.2007073751311115 |
|view      |unknown       |medium     |afternoon  |2199336|0.05181154391209129  |5.181154391209129  |
|view      |unknown       |low        |afternoon  |2067948|0.048716330115053524 |4.871633011505352  |
|view      |electronics   |high       |morning    |1882043|0.044336815083708916 |4.433681508370892  |
|view      |unknown       |medium     |morning    |1833877|0.04320212951312316  |4.320212951312316  |
|view      |unknown       |low        |morning    |1801412|0.042437325148030225 |4.243732514803023  |
|view      |electronics   |medium     |night      |1403775|0.033069867476000006 |3.3069867476000008 |
|view      |unknown       |medium     |night      |1050138|0.02473895352995437  |2.473895352995437  |
|view      |unknown       |low        |night      |1034555|0.02437185214627215  |2.437185214627215  |
|view      |appliances    |medium     |afternoon  |977696 |0.02303237851636858  |2.303237851636858  |
|view      |electronics   |high       |night      |969987 |0.02285077134401369  |2.285077134401369  |
|view      |appliances    |medium     |morning    |918761 |0.021643998868848102 |2.1643998868848104 |
|view      |electronics   |medium     |evening    |905138 |0.021323070796596105 |2.1323070796596104 |
|view      |electronics   |high       |evening    |779740 |0.018368968293163965 |1.8368968293163965 |
|view      |unknown       |medium     |evening    |725742 |0.017096893563261346 |1.7096893563261346 |
|view      |unknown       |low        |evening    |723841 |0.017052110162736424 |1.7052110162736425 |
|view      |unknown       |high       |afternoon  |688968 |0.016230578586457784 |1.6230578586457785 |
|view      |unknown       |high       |morning    |559329 |0.013176567402527904 |1.3176567402527903 |
|view      |appliances    |medium     |night      |490580 |0.011556991388488955 |1.1556991388488955 |
|view      |appliances    |low        |afternoon  |467390 |0.011010685729271176 |1.1010685729271175 |
|view      |electronics   |low        |afternoon  |464945 |0.010953086879043169 |1.0953086879043168 |
|view      |appliances    |low        |morning    |461814 |0.010879327369814585 |1.0879327369814584 |
|view      |computers     |high       |afternoon  |443277 |0.010442636209619672 |1.0442636209619671 |
|view      |electronics   |low        |morning    |390964 |0.009210256392859871 |0.9210256392859871 |
|view      |computers     |high       |morning    |369171 |0.008696860996942102 |0.8696860996942103 |
|view      |apparel       |medium     |afternoon  |356110 |0.008389172415008361 |0.8389172415008361 |
|view      |appliances    |high       |afternoon  |327443 |0.007713840619717455 |0.7713840619717455 |
|view      |unknown       |high       |night      |324542 |0.007645499407238336 |0.7645499407238336 |
|view      |computers     |medium     |afternoon  |300349 |0.007075565262630497 |0.7075565262630497 |
|view      |furniture     |medium     |afternoon  |287383 |0.006770114672832406 |0.6770114672832406 |
|view      |appliances    |high       |morning    |279811 |0.006591734920715241 |0.6591734920715241 |
|view      |computers     |medium     |morning    |270616 |0.006375120839796419 |0.6375120839796419 |
|view      |apparel       |medium     |morning    |261197 |0.006153229808999857 |0.6153229808999857 |
|view      |apparel       |low        |afternoon  |259689 |0.0061177046285729305|0.6117704628572931 |
|view      |appliances    |medium     |evening    |254456 |0.005994426598616629 |0.5994426598616629 |
|view      |auto          |medium     |afternoon  |251946 |0.0059352964906116   |0.5935296490611599 |
|view      |appliances    |low        |night      |249802 |0.005884788541781805 |0.5884788541781806 |
|view      |furniture     |medium     |morning    |230530 |0.00543078238980056  |0.543078238980056  |
|view      |unknown       |high       |evening    |226770 |0.0053422050168527874|0.5342205016852788 |
|view      |electronics   |low        |night      |211843 |0.00499055755781252  |0.499055755781252  |
|view      |auto          |medium     |morning    |205052 |0.004830576456831582 |0.4830576456831582 |
|view      |apparel       |low        |morning    |200917 |0.004733164904400985 |0.47331649044009855|
|view      |computers     |high       |night      |187786 |0.004423827275630452 |0.44238272756304514|
|cart      |electronics   |medium     |morning    |173897 |0.0040966328253986386|0.40966328253986384|
|view      |electronics   |low        |evening    |166446 |0.003921103568527932 |0.39211035685279316|
|view      |computers     |high       |evening    |157419 |0.003708447200017414 |0.3708447200017414 |
|view      |construction  |medium     |afternoon  |155224 |0.003656737802777956 |0.36567378027779557|
|view      |appliances    |high       |night      |151480 |0.00356853735482145  |0.356853735482145  |
+----------+--------------+-----------+-----------+-------+---------------------+-------------------+
only showing top 50 rows

In [ ]:
# Guardar las principales combinaciones de particionamiento
top_partition_combinations = partition_combinations.orderBy(desc("count")).limit(20)

top_partition_combinations_pd = top_partition_combinations.toPandas()
top_partition_combinations_pd

,event_type,category_group,price_range,time_period,count,probability,percentage
0,view,electronics,medium,afternoon,3060638,0.072102,7.210193
1,view,electronics,medium,morning,2595235,0.061138,6.113806
2,view,electronics,high,afternoon,2207636,0.052007,5.200707
3,view,unknown,medium,afternoon,2199336,0.051812,5.181154
4,view,unknown,low,afternoon,2067948,0.048716,4.871633
5,view,electronics,high,morning,1882043,0.044337,4.433682
6,view,unknown,medium,morning,1833877,0.043202,4.320213
7,view,unknown,low,morning,1801412,0.042437,4.243733
8,view,electronics,medium,night,1403775,0.033070,3.306987
9,view,unknown,medium,night,1050138,0.024739,2.473895
10,view,unknown,low,night,1034555,0.024372,2.437185
11,view,appliances,medium,afternoon,977696,0.023032,2.303238
12,view,electronics,high,night,969987,0.022851,2.285077
13,view,appliances,medium,morning,918761,0.021644,2.164400
14,view,electronics,medium,evening,905138,0.021323,2.132307
15,view,electronics,high,evening,779740,0.018369,1.836897
16,view,unknown,medium,evening,725742,0.017097,1.709689
17,view,unknown,low,evening,723841,0.017052,1.705211
18,view,unknown,high,afternoon,688968,0.016231,1.623058
19,view,unknown,high,morning,559329,0.013177,1.317657

## Extracción de muestras de ejemplo por regla de particionamiento

En esta sección se muestran ejemplos de extracción de registros que cumplen con reglas específicas de particionamiento. Cada regla se define por la combinación de cuatro variables: `event_type`, `category_group`, `price_range` y `time_period`.

El objetivo de esta etapa no es construir todavía la muestra final de entrenamiento o prueba, sino comprobar que el código permite recuperar correctamente subconjuntos de la base de datos original D de acuerdo con las reglas definidas en la etapa de particionamiento.

In [ ]:
def extraer_muestra_particion(event_type, category_group, price_range, time_period, n=10):
    """
    Filtra la base particionada usando una regla de particionamiento
    y muestra una muestra de ejemplo de n registros.
    """

    particion = df_part.filter(
        (col("event_type") == event_type) &
        (col("category_group") == category_group) &
        (col("price_range") == price_range) &
        (col("time_period") == time_period)
    )

    total_registros = particion.count()

    print("Regla de particionamiento:")
    print(f"event_type = {event_type}")
    print(f"category_group = {category_group}")
    print(f"price_range = {price_range}")
    print(f"time_period = {time_period}")
    print(f"Total de registros en la partición: {total_registros:,}")

    particion.show(n, truncate=False)

    return particion

In [ ]:
#Ejemplo 1
muestra_p1 = extraer_muestra_particion(
    event_type="view",
    category_group="electronics",
    price_range="medium",
    time_period="morning",
    n=10
)

Regla de particionamiento:
event_type = view
category_group = electronics
price_range = medium
time_period = morning
Total de registros en la partición: 2,595,235
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code         |brand  |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 06:00:00|view      |1004768   |2053013555631882655|electronics.smartphone|samsung|253.31|551086352|ea5e607f-86b0-4f82-a982-53fcbee2408f|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:00|view      |1005153   |2053013555631882655|electronics.smartphone|xiaomi |231.64|514501121|29a4ca4c-6d44-4647-9dbd-7ac8bb89b6a3|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:00|view      |21410469  |2053013561579406073|electronics.clocks    |NULL   |266.93|546501957|2870c258-5bfc-4e46-a4bb-6bc5cdbdc14a|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |1004750   |2053013555631882655|electronics.smartphone|samsung|203.35|514566777|d11317ad-5df8-4656-9dd4-8eef059b72ea|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |1201504   |2172371436436455782|electronics.tablet    |samsung|164.17|555504176|0f0ac4ce-2779-4a50-89e5-4a3efd272c63|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |1004776   |2053013555631882655|electronics.smartphone|xiaomi |185.08|548204604|0f2fd799-ea44-4e99-85ae-4b6a3f9ed03d|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |1801739   |2053013554415534427|electronics.video.tv  |samsung|282.2 |522706775|e86ee82b-521f-4326-a7c6-017e86dddcd7|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |1004937   |2053013555631882655|electronics.smartphone|vivo   |167.29|540221506|b0ce4784-9b00-4a00-bf42-4158860f2765|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |1004426   |2053013555631882655|electronics.smartphone|samsung|217.04|548706274|264fe3f8-357e-4127-972b-a93069178f55|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:02|view      |1005159   |2053013555631882655|electronics.smartphone|xiaomi |231.41|530709499|99060310-3fa5-4c16-946b-2ce2b031429a|electronics   |6         |morning    |medium     |
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 10 rows

In [ ]:
#Ejemplo 2
muestra_p2 = extraer_muestra_particion(
    event_type="view",
    category_group="electronics",
    price_range="medium",
    time_period="night",
    n=10
)

Regla de particionamiento:
event_type = view
category_group = electronics
price_range = medium
time_period = night
Total de registros en la partición: 1,403,775
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code              |brand  |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 00:00:18|view      |1801995   |2053013554415534427|electronics.video.tv       |haier  |193.03|537192226|e3151795-c355-4efa-acf6-e1fe1bebeee5|electronics   |0         |night      |medium     |
|2019-10-01 00:00:23|view      |1004739   |2053013555631882655|electronics.smartphone     |xiaomi |197.55|519530528|9882d21f-2c5f-496b-90d4-a1503edb6562|electronics   |0         |night      |medium     |
|2019-10-01 00:00:36|view      |1004767   |2053013555631882655|electronics.smartphone     |samsung|254.82|512558158|9a206ba2-37c7-4354-9d31-37ff3bb297ed|electronics   |0         |night      |medium     |
|2019-10-01 00:00:58|view      |4802639   |2053013554658804075|electronics.audio.headphone|sony   |218.77|514808401|1877639d-46a4-44f8-bae9-a14456952240|electronics   |0         |night      |medium     |
|2019-10-01 00:01:04|view      |1004870   |2053013555631882655|electronics.smartphone     |samsung|286.86|516489361|7d6d03fb-39d6-4143-8694-981a550acaaa|electronics   |0         |night      |medium     |
|2019-10-01 00:01:06|view      |1004856   |2053013555631882655|electronics.smartphone     |samsung|130.76|555447788|94c1a98c-41a3-401e-ad99-439beac4495c|electronics   |0         |night      |medium     |
|2019-10-01 00:01:11|view      |1004836   |2053013555631882655|electronics.smartphone     |samsung|241.19|546259103|6e2984c8-502e-4fe7-bbba-34087f760175|electronics   |0         |night      |medium     |
|2019-10-01 00:01:16|view      |1004497   |2053013555631882655|electronics.smartphone     |nokia  |159.33|550859983|4718c88d-1892-4a5f-931a-f61ad7a20459|electronics   |0         |night      |medium     |
|2019-10-01 00:01:17|view      |1004856   |2053013555631882655|electronics.smartphone     |samsung|130.76|515757896|4938043e-e50f-44ad-944d-958d04df62d6|electronics   |0         |night      |medium     |
|2019-10-01 00:01:24|view      |1004785   |2053013555631882655|electronics.smartphone     |huawei |278.55|514336739|cccc58c1-4986-4d08-b595-d837c0c7d514|electronics   |0         |night      |medium     |
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 10 rows

In [ ]:
#Ejemplo 3
muestra_p3 = extraer_muestra_particion(
    event_type="view",
    category_group="electronics",
    price_range="high",
    time_period="morning",
    n=10
)

Regla de particionamiento:
event_type = view
category_group = electronics
price_range = high
time_period = morning
Total de registros en la partición: 1,882,043
+-------------------+----------+----------+-------------------+----------------------+-------+-------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code         |brand  |price  |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+----------------------+-------+-------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 06:00:01|view      |1004873   |2053013555631882655|electronics.smartphone|samsung|388.81 |518566925|6a7a239d-36de-432a-a59a-8beec5a2f9b9|electronics   |6         |morning    |high       |
|2019-10-01 06:00:02|view      |1801712   |2053013554415534427|electronics.video.tv  |lg     |365.49 |555497594|381597c0-3e5e-4c30-b965-dbb03ac97d79|electronics   |6         |morning    |high       |
|2019-10-01 06:00:02|view      |1002099   |2053013555631882655|electronics.smartphone|samsung|370.41 |539278651|c9919f46-a5c1-4da0-ac19-558551201904|electronics   |6         |morning    |high       |
|2019-10-01 06:00:03|view      |1004249   |2053013555631882655|electronics.smartphone|apple  |738.61 |543421006|ece876ee-b9e7-4558-8f59-1305041d2368|electronics   |6         |morning    |high       |
|2019-10-01 06:00:03|view      |1005016   |2053013555631882655|electronics.smartphone|samsung|615.56 |516224905|73d5d942-2868-4f63-ba71-5075a6c8b5bc|electronics   |6         |morning    |high       |
|2019-10-01 06:00:04|view      |1003306   |2053013555631882655|electronics.smartphone|apple  |587.56 |555483758|0fcbb890-4eca-4583-86b3-0c95e61e04c1|electronics   |6         |morning    |high       |
|2019-10-01 06:00:04|view      |1801904   |2053013554415534427|electronics.video.tv  |samsung|481.09 |545501536|6dbbe389-cd32-4f6a-b304-2426b851fa6a|electronics   |6         |morning    |high       |
|2019-10-01 06:00:04|view      |1005105   |2053013555631882655|electronics.smartphone|apple  |1415.48|512616014|7089229f-5fcb-4290-8e4f-d8148fe88f8e|electronics   |6         |morning    |high       |
|2019-10-01 06:00:05|view      |1004875   |2053013555631882655|electronics.smartphone|samsung|388.68 |555499658|bdc33454-cfbe-4d51-9f2c-06d45287a9ac|electronics   |6         |morning    |high       |
|2019-10-01 06:00:05|view      |1005115   |2053013555631882655|electronics.smartphone|apple  |975.57 |516340282|48173be1-9f2f-4f02-9d2a-de80f0885579|electronics   |6         |morning    |high       |
+-------------------+----------+----------+-------------------+----------------------+-------+-------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 10 rows

In [ ]:
#Ejemplo 4
muestra_purchase = extraer_muestra_particion(
    event_type="purchase",
    category_group="electronics",
    price_range="medium",
    time_period="morning",
    n=10
)

Regla de particionamiento:
event_type = purchase
category_group = electronics
price_range = medium
time_period = morning
Total de registros en la partición: 103,841
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code              |brand  |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 06:00:11|purchase  |1801766   |2053013554415534427|electronics.video.tv       |artel  |150.7 |515807042|d93a48cc-8b48-40b4-99dc-be5af45166cf|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:18|purchase  |1004767   |2053013555631882655|electronics.smartphone     |samsung|254.76|521333161|fb000b95-5cd4-4ef3-b556-1922ac89b0c9|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:24|purchase  |1004886   |2053013555631882655|electronics.smartphone     |oppo   |153.04|555502610|83b4ce52-9666-4820-9a8a-8022162efdbf|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:27|purchase  |1004741   |2053013555631882655|electronics.smartphone     |xiaomi |185.71|512696270|d63359a0-0922-4995-93aa-906dbb92ba28|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:31|purchase  |1005003   |2053013555631882655|electronics.smartphone     |huawei |258.18|526180275|3c4ca2f9-44fa-429b-bbcf-24ca75035e03|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:39|purchase  |1004750   |2053013555631882655|electronics.smartphone     |samsung|203.35|552297980|8cfbff7f-1c95-4be4-b8e4-5669a8fba266|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:46|purchase  |1004836   |2053013555631882655|electronics.smartphone     |samsung|241.18|514471892|a5dc9fcc-42c4-4c5e-bd64-070f6ca7c106|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:58|purchase  |1004739   |2053013555631882655|electronics.smartphone     |xiaomi |197.52|541311429|4121c475-5863-441e-b440-b3a1c566fe42|electronics   |6         |morning    |medium     |
|2019-10-01 06:01:02|purchase  |1005003   |2053013555631882655|electronics.smartphone     |huawei |258.18|519473836|05735499-067d-4079-8766-338adf1e81ff|electronics   |6         |morning    |medium     |
|2019-10-01 06:01:06|purchase  |4804055   |2053013554658804075|electronics.audio.headphone|apple  |188.73|512850441|e5c3cc9c-452d-4f20-b422-ae880928fd60|electronics   |6         |morning    |medium     |
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 10 rows

In [ ]:
#Extraer las 10 reglas de particionamiento más frecuentes
top_10_rules = partition_combinations.orderBy(desc("count")).limit(10).collect()

for i, rule in enumerate(top_10_rules, start=1):
    print("=" * 80)
    print(f"Muestra de ejemplo para la partición P{i}")

    muestra = df_part.filter(
        (col("event_type") == rule["event_type"]) &
        (col("category_group") == rule["category_group"]) &
        (col("price_range") == rule["price_range"]) &
        (col("time_period") == rule["time_period"])
    )

    print(f"event_type: {rule['event_type']}")
    print(f"category_group: {rule['category_group']}")
    print(f"price_range: {rule['price_range']}")
    print(f"time_period: {rule['time_period']}")
    print(f"Registros en la partición: {rule['count']:,}")
    print(f"Probabilidad: {rule['probability']:.4f}")
    print(f"Porcentaje: {rule['percentage']:.2f}%")

    muestra.show(5, truncate=False)

================================================================================
Muestra de ejemplo para la partición P1
event_type: view
category_group: electronics
price_range: medium
time_period: afternoon
Registros en la partición: 3,060,638
Probabilidad: 0.0721
Porcentaje: 7.21%
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code              |brand  |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 12:00:00|view      |1004863   |2053013555631882655|electronics.smartphone     |samsung|174.38|554989582|3be9234f-5119-4f9c-900e-b15db47b2321|electronics   |12        |afternoon  |medium     |
|2019-10-01 12:00:00|view      |1005069   |2053013555631882655|electronics.smartphone     |vivo   |308.86|512431118|0dccf636-2385-45b5-a59b-01bbe31f3731|electronics   |12        |afternoon  |medium     |
|2019-10-01 12:00:00|view      |1004402   |2053013555631882655|electronics.smartphone     |xiaomi |164.17|548847592|fb0137d7-65f5-4e03-b446-2dbd45f6f30a|electronics   |12        |afternoon  |medium     |
|2019-10-01 12:00:00|view      |1004741   |2053013555631882655|electronics.smartphone     |xiaomi |185.82|512962555|3f7432de-eb11-4970-b473-32af737b91ed|electronics   |12        |afternoon  |medium     |
|2019-10-01 12:00:01|view      |4804409   |2053013554658804075|electronics.audio.headphone|elari  |66.87 |518891113|fc1f1b5f-15bc-47f5-b850-c6e7c841e67e|electronics   |12        |afternoon  |medium     |
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P2
event_type: view
category_group: electronics
price_range: medium
time_period: morning
Registros en la partición: 2,595,235
Probabilidad: 0.0611
Porcentaje: 6.11%
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code         |brand  |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 06:00:00|view      |1004768   |2053013555631882655|electronics.smartphone|samsung|253.31|551086352|ea5e607f-86b0-4f82-a982-53fcbee2408f|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:00|view      |1005153   |2053013555631882655|electronics.smartphone|xiaomi |231.64|514501121|29a4ca4c-6d44-4647-9dbd-7ac8bb89b6a3|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:00|view      |21410469  |2053013561579406073|electronics.clocks    |NULL   |266.93|546501957|2870c258-5bfc-4e46-a4bb-6bc5cdbdc14a|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |1004750   |2053013555631882655|electronics.smartphone|samsung|203.35|514566777|d11317ad-5df8-4656-9dd4-8eef059b72ea|electronics   |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |1201504   |2172371436436455782|electronics.tablet    |samsung|164.17|555504176|0f0ac4ce-2779-4a50-89e5-4a3efd272c63|electronics   |6         |morning    |medium     |
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P3
event_type: view
category_group: electronics
price_range: high
time_period: afternoon
Registros en la partición: 2,207,636
Probabilidad: 0.0520
Porcentaje: 5.20%
+-------------------+----------+----------+-------------------+----------------------+-------+-------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code         |brand  |price  |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+----------------------+-------+-------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 12:00:00|view      |1004946   |2053013555631882655|electronics.smartphone|oneplus|746.22 |514609647|51a63582-5d97-493c-bc13-fc458a44fae7|electronics   |12        |afternoon  |high       |
|2019-10-01 12:00:00|view      |1005133   |2053013555631882655|electronics.smartphone|apple  |1619.09|512800568|d3f649a2-58df-47a5-837a-a49cfde57847|electronics   |12        |afternoon  |high       |
|2019-10-01 12:00:00|view      |1201389   |2172371436436455782|electronics.tablet    |apple  |926.38 |515242163|c95d0a12-3b7f-457e-bff1-3eefe5a7f73c|electronics   |12        |afternoon  |high       |
|2019-10-01 12:00:00|view      |1004213   |2053013555631882655|electronics.smartphone|xiaomi |503.37 |543639295|e795b3d0-522a-41bc-a819-aa365850e95b|electronics   |12        |afternoon  |high       |
|2019-10-01 12:00:00|view      |1004227   |2053013555631882655|electronics.smartphone|apple  |1012.77|553189926|803a3b48-ebef-4728-8dbf-046730188494|electronics   |12        |afternoon  |high       |
+-------------------+----------+----------+-------------------+----------------------+-------+-------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P4
event_type: view
category_group: unknown
price_range: medium
time_period: afternoon
Registros en la partición: 2,199,336
Probabilidad: 0.0518
Porcentaje: 5.18%
+-------------------+----------+----------+-------------------+-------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code|brand  |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+-------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 12:00:00|view      |26402552  |2053013563651392361|NULL         |NULL   |314.36|518856717|5980d9f6-cd72-477b-ba02-77154119fb30|unknown       |12        |afternoon  |medium     |
|2019-10-01 12:00:01|view      |27201245  |2053013564154708873|NULL         |NULL   |216.22|516649952|dfeb673a-0684-4601-baad-40198e117281|unknown       |12        |afternoon  |medium     |
|2019-10-01 12:00:01|view      |16500000  |2053013556462354899|NULL         |omron  |92.64 |536566570|83e22c6b-fbf9-4ee7-8578-14853b880316|unknown       |12        |afternoon  |medium     |
|2019-10-01 12:00:02|view      |26203329  |2053013563693335403|NULL         |sokolov|308.63|531880924|509a3eb0-a675-44fd-889e-523c9b6f249e|unknown       |12        |afternoon  |medium     |
|2019-10-01 12:00:03|view      |5100746   |2053013553375346967|NULL         |huawei |76.7  |551713600|74d3f65d-b0c0-4e2c-a6dc-6a10accf7482|unknown       |12        |afternoon  |medium     |
+-------------------+----------+----------+-------------------+-------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P5
event_type: view
category_group: unknown
price_range: low
time_period: afternoon
Registros en la partición: 2,067,948
Probabilidad: 0.0487
Porcentaje: 4.87%
+-------------------+----------+----------+-------------------+-------------+-------+-----+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code|brand  |price|user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+-------------+-------+-----+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 12:00:01|view      |17400135  |2053013558727279193|NULL         |NULL   |4.56 |517697264|aa58b3c3-7387-4173-8527-242b6ac0d256|unknown       |12        |afternoon  |low        |
|2019-10-01 12:00:01|view      |8000330   |2053013556579795419|NULL         |bertoni|54.83|539432346|4d7c8c88-4cc8-4400-9497-e25e68aaa547|unknown       |12        |afternoon  |low        |
|2019-10-01 12:00:02|view      |12500527  |2053013556277805513|NULL         |crown  |47.62|546359206|8cccee01-7542-49a7-bc26-21d9ffb70b20|unknown       |12        |afternoon  |low        |
|2019-10-01 12:00:03|view      |18000958  |2053013558525952589|NULL         |samsung|15.42|555614010|a6e20610-4a6e-41a6-abcf-cdd83f30914f|unknown       |12        |afternoon  |low        |
|2019-10-01 12:00:03|view      |5300650   |2053013563173241677|NULL         |vitek  |12.84|548531598|d7a9fb7c-e136-41dc-8fe3-002f1c413402|unknown       |12        |afternoon  |low        |
+-------------------+----------+----------+-------------------+-------------+-------+-----+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P6
event_type: view
category_group: electronics
price_range: high
time_period: morning
Registros en la partición: 1,882,043
Probabilidad: 0.0443
Porcentaje: 4.43%
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code         |brand  |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 06:00:01|view      |1004873   |2053013555631882655|electronics.smartphone|samsung|388.81|518566925|6a7a239d-36de-432a-a59a-8beec5a2f9b9|electronics   |6         |morning    |high       |
|2019-10-01 06:00:02|view      |1801712   |2053013554415534427|electronics.video.tv  |lg     |365.49|555497594|381597c0-3e5e-4c30-b965-dbb03ac97d79|electronics   |6         |morning    |high       |
|2019-10-01 06:00:02|view      |1002099   |2053013555631882655|electronics.smartphone|samsung|370.41|539278651|c9919f46-a5c1-4da0-ac19-558551201904|electronics   |6         |morning    |high       |
|2019-10-01 06:00:03|view      |1004249   |2053013555631882655|electronics.smartphone|apple  |738.61|543421006|ece876ee-b9e7-4558-8f59-1305041d2368|electronics   |6         |morning    |high       |
|2019-10-01 06:00:03|view      |1005016   |2053013555631882655|electronics.smartphone|samsung|615.56|516224905|73d5d942-2868-4f63-ba71-5075a6c8b5bc|electronics   |6         |morning    |high       |
+-------------------+----------+----------+-------------------+----------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P7
event_type: view
category_group: unknown
price_range: medium
time_period: morning
Registros en la partición: 1,833,877
Probabilidad: 0.0432
Porcentaje: 4.32%
+-------------------+----------+----------+-------------------+-------------+-----------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code|brand      |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+-------------+-----------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 06:00:00|view      |13300471  |2053013557166998015|NULL         |NULL       |185.33|512422621|d7651793-4ced-4db7-af5a-1e0e3b699ae8|unknown       |6         |morning    |medium     |
|2019-10-01 06:00:00|view      |44100007  |2100065069302809284|NULL         |NULL       |159.59|549944313|2f4f8d59-18c9-456b-b41c-ad89bec31955|unknown       |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |12700523  |2053013553559896355|NULL         |continental|123.68|521856383|d5235a7f-344e-4d5b-ab5a-a8862d0b51f3|unknown       |6         |morning    |medium     |
|2019-10-01 06:00:01|view      |26300077  |2053013563584283495|NULL         |lucente    |237.33|526036242|75e26ec5-1ebf-4666-9354-f042b247142a|unknown       |6         |morning    |medium     |
|2019-10-01 06:00:02|view      |30100011  |2053013556110033341|NULL         |bosch      |74.62 |513193063|d3cb9043-35d6-47ec-ab24-72f62fb5efab|unknown       |6         |morning    |medium     |
+-------------------+----------+----------+-------------------+-------------+-----------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P8
event_type: view
category_group: unknown
price_range: low
time_period: morning
Registros en la partición: 1,801,412
Probabilidad: 0.0424
Porcentaje: 4.24%
+-------------------+----------+----------+-------------------+-------------+-----+-----+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code|brand|price|user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+-------------+-----+-----+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 06:00:00|view      |45100027  |2106075725441269865|NULL         |bot  |2.83 |553682531|e5126502-73d8-4131-bbda-0bb0827d275f|unknown       |6         |morning    |low        |
|2019-10-01 06:00:00|view      |19600368  |2053013558836331105|NULL         |NULL |17.62|512824179|53d76404-7b00-4c67-b5df-549d6d3ec442|unknown       |6         |morning    |low        |
|2019-10-01 06:00:00|view      |15901529  |2053013558190408249|NULL         |NULL |30.89|553405468|55249608-3159-4d1a-ab14-c3b59e41d81c|unknown       |6         |morning    |low        |
|2019-10-01 06:00:00|view      |32402992  |2053013566562238479|NULL         |NULL |7.34 |512513760|40db32b0-9412-45da-bf83-dc2b64cd302a|unknown       |6         |morning    |low        |
|2019-10-01 06:00:00|view      |27300020  |2053013563366179673|NULL         |NULL |60.66|535814305|0e60e1d1-282a-4c1f-a8c4-9603794d30cd|unknown       |6         |morning    |low        |
+-------------------+----------+----------+-------------------+-------------+-----+-----+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P9
event_type: view
category_group: electronics
price_range: medium
time_period: night
Registros en la partición: 1,403,775
Probabilidad: 0.0331
Porcentaje: 3.31%
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code              |brand  |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 00:00:18|view      |1801995   |2053013554415534427|electronics.video.tv       |haier  |193.03|537192226|e3151795-c355-4efa-acf6-e1fe1bebeee5|electronics   |0         |night      |medium     |
|2019-10-01 00:00:23|view      |1004739   |2053013555631882655|electronics.smartphone     |xiaomi |197.55|519530528|9882d21f-2c5f-496b-90d4-a1503edb6562|electronics   |0         |night      |medium     |
|2019-10-01 00:00:36|view      |1004767   |2053013555631882655|electronics.smartphone     |samsung|254.82|512558158|9a206ba2-37c7-4354-9d31-37ff3bb297ed|electronics   |0         |night      |medium     |
|2019-10-01 00:00:58|view      |4802639   |2053013554658804075|electronics.audio.headphone|sony   |218.77|514808401|1877639d-46a4-44f8-bae9-a14456952240|electronics   |0         |night      |medium     |
|2019-10-01 00:01:04|view      |1004870   |2053013555631882655|electronics.smartphone     |samsung|286.86|516489361|7d6d03fb-39d6-4143-8694-981a550acaaa|electronics   |0         |night      |medium     |
+-------------------+----------+----------+-------------------+---------------------------+-------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
only showing top 5 rows
================================================================================
Muestra de ejemplo para la partición P10
event_type: view
category_group: unknown
price_range: medium
time_period: night
Registros en la partición: 1,050,138
Probabilidad: 0.0247
Porcentaje: 2.47%
+-------------------+----------+----------+-------------------+-------------+----------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|event_time         |event_type|product_id|category_id        |category_code|brand     |price |user_id  |user_session                        |category_group|event_hour|time_period|price_range|
+-------------------+----------+----------+-------------------+-------------+----------+------+---------+------------------------------------+--------------+----------+-----------+-----------+
|2019-10-01 00:00:24|view      |34700031  |2061717937420501730|NULL         |NULL      |151.87|539512263|f27a45f8-fb98-459a-96a6-45271f56a987|unknown       |0         |night      |medium     |
|2019-10-01 00:00:25|view      |19001139  |2053013557225718275|NULL         |gran-stone|67.58 |525734504|83f584ed-c7f7-442e-8ae9-713cb27fdece|unknown       |0         |night      |medium     |

In [ ]:
# Ejemplo de muestreo estratificado proporcional
# En esta etapa solo se muestra cómo se podría aplicar posteriormente.

sample_fraction = 0.001  # 0.1% de cada partición, ejemplo

sample_df = df_part.sampleBy(
    "event_type",
    fractions={
        "view": sample_fraction,
        "cart": sample_fraction,
        "purchase": sample_fraction
    },
    seed=42
)

sample_df.groupBy("event_type").count().show()

+----------+-----+
|event_type|count|
+----------+-----+
|  purchase|  783|
|      view|40927|
|      cart|  892|
+----------+-----+

In [ ]:
from pyspark.sql.functions import concat_ws

# Crear una llave única de partición
df_part = df_part.withColumn(
    "partition_key",
    concat_ws(
        "_",
        "event_type",
        "category_group",
        "price_range",
        "time_period"
    )
)

df_part.select(
    "event_type",
    "category_group",
    "price_range",
    "time_period",
    "partition_key"
).show(10, truncate=False)

+----------+--------------+-----------+-----------+---------------------------+
|event_type|category_group|price_range|time_period|partition_key              |
+----------+--------------+-----------+-----------+---------------------------+
|view      |unknown       |low        |night      |view_unknown_low_night     |
|view      |appliances    |low        |night      |view_appliances_low_night  |
|view      |furniture     |high       |night      |view_furniture_high_night  |
|view      |computers     |medium     |night      |view_computers_medium_night|
|view      |electronics   |high       |night      |view_electronics_high_night|
|view      |computers     |high       |night      |view_computers_high_night  |
|view      |unknown       |high       |night      |view_unknown_high_night    |
|view      |unknown       |low        |night      |view_unknown_low_night     |
|view      |apparel       |medium     |night      |view_apparel_medium_night  |
|view      |electronics   |high       |night      |view_electronics_high_night|
+----------+--------------+-----------+-----------+---------------------------+
only showing top 10 rows

## Técnica de muestreo propuesta

Para la construcción de la muestra representativa M se propone utilizar muestreo estratificado proporcional por partición. Cada partición está definida por la combinación de `event_type`, `category_group`, `price_range` y `time_period`.

La muestra se obtendrá seleccionando registros de cada partición de acuerdo con la proporción que dicha partición representa dentro de la población original. Esto permite conservar la estructura de la base D y reducir el riesgo de sesgo, especialmente porque el dataset presenta un fuerte desbalance entre eventos de visualización, carrito y compra.